### ISSUE TITLE
Not working!(Alt name: first test)

### ISSUE THREAD

**Issue by predefine** [raspiduino/uARM8266#3]
```
.........
Connected to WiFi successfully. IP: 192.168.1.117
Starting websocket server on port 1234
Is server live? 1
Please connect to this webSocket server now!
Client connected. Client version: test
Starting emulator...

--------------- CUT HERE FOR EXCEPTION DECODER ---------------

Exception (28):
epc1=0x40205dbc epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000000 depc=0x00000000

>>>stack>>>

ctx: cont
sp: 3ffffd60 end: 3fffffd0 offset: 0150
3ffffeb0:  00000000 00000000 6e6f2000 3fff26d4
3ffffec0:  3ffeec18 402473cc 00000000 4020bbdc
3ffffed0:  72617453 676e6974 756d6520 00000004
3ffffee0:  3fffff40 3ffef04c 3ffef048 40204462
3ffffef0:  3fffff44 000000c2 3ffe85e0 401006ea
3fffff00:  00000000 00000001 00000000 4020524f
3fffff10:  00000000 00000000 00000000 00000000
3fffff20:  3fff20d8 00000001 3fffff70 00000000
3fffff30:  00000001 00000000 3ffeee40 40203647
3fffff40:  3fff2308 7501a8c0 00000000 4020dc10
3fffff50:  00000000 00000001 00000080 40203f18
3fffff60:  4020b7d4 3ffe8913 3fff26d4 3fff2868
3fffff70:  3fff1d54 00000001 3ffeec18 40203fa2
3fffff80:  00000000 3ffeec18 3fff26d4 40206b2e
3fffff90:  00000000 feefeffe feefeffe feefeffe
3fffffa0:  00000000 00000000 00000000 00000000
3fffffb0:  3fffdad0 00000000 3fff283c 4020ce50
3fffffc0:  feefeffe feefeffe 3fffdab0 40100d05
<<<stack<<<

--------------- CUT HERE FOR EXCEPTION DECODER ---------------

 ets Jan  8 2013,rst cause:2, boot mode:(3,7)

load 0x4010f000, len 3424, room 16
tail 0
chksum 0x2e
load 0x3fff20b8, len 40, room 8
tail 0
chksum 0x2b
csum 0x2b
v0004f460
~ld
n�r�|�l
       �l`b
           brl�bn
                 l`rl��

                       uARM on esp8266
Copyright (C) Dmitry Grinberg (dmtirygr@gmail.com)
Ported to esp8266 by Giang Vinh Loc (giangvinhloc610@gmail.com)
```
wscat:
```
> user@debian:~$ wscat --connect ws://192.168.1.117:1234
Connected (press CTRL+C to quit)
> test
< connected
>
```

**Comment by raspiduino** [comment]
> This thing haven't been tested once, so you have to expect to encounter errors.

Honestly this is one of the worst quality project of mine: I created it but due to lack of devices and time, I cannot test it. I plan to rework on it later, but currently I can't go back into this. Sorry :(

**Comment by predefine** [comment]
uh, okay
goodluck with other projects, currently im trying port mini-rv32ima to esp8266 with network as ram

**Comment by raspiduino** [comment]
> goodluck with other projects, currently im trying port mini-rv32ima to esp8266 with network as ram

NICE! When you are done, please tell me. Thank you!

**Comment by predefine** [comment]
> > goodluck with other projects, currently im trying port mini-rv32ima to esp8266 with network as ram
> 
> NICE! When you are done, please tell me. Thank you!

after 1 hour i dont have any uart output, but linux is loading (i guess yes)

**Comment by raspiduino** [comment]
> after 1 hour i dont have any uart output, but linux is loading (i guess yes)

If you wait 8 hours but nothing output then something might be wrong, since Arduino UNO boot time is 8 hours (and esp8266 can't be slower than that)

**Comment by predefine** [comment]
> > after 1 hour i dont have any uart output, but linux is loading (i guess yes)
> 
> If you wait 8 hours but nothing output then something might be wrong, since Arduino UNO boot time is 8 hours (and esp8266 can't be slower than that)

ig 5 hours and nothing
